REM preguntas
CLS
INPUT "teclee su nombre "; a$
PRINT "geografia"
INPUT "diga cuantos km tiene el nilo"; i
PRINT "astronomia"
INPUT "diga done se encuentra  un crater en la tierra que tiene 200m de profundida"; m$
PRINT "historia"
INPUT "diga el nomnbre del arqueologo que descubrio la tumba de tutankamon"; g$
PRINT "literatura"
INPUT "diga el nombre del autor del libro la vuelta al mundo en 80 dias"; y$
PRINT "matematica"
INPUT "cuanto es 20*5+67"; u
PRINT "ciencia"
INPUT "diga el nombre del personaje que formulo la teoria de la relatividad"; k$
IF i = 6671 THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
IF m = arizona THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
IF g = carter THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
IF y = julio THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
IF u = 167 THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
IF k = Enstein THEN PRINT "corecto ";  ELSE PRINT ; "incorecto"
END

